# Activating the default profile
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# General settings Spring Boot
spring.main.banner-mode=console
spring.jpa.open-in-view=false

# General bot settings
telegram.bot.token=${BOT_TOKEN:}

# Server Port
server.port=${SERVER_PORT:8080}