spring.datasource.url=jdbc:postgresql://localhost:5433/telegram_bot01
spring.datasource.username=SendMeReminder
spring.datasource.password=QwertY
telegram.bot.token=7513242957:AAFPc3-0epTXzSZAIJfLCGxbHd1g5l0NA9g

logging.level.pro.sky.telegrambot=DEBUG