# Activating the default profile
spring.profiles.active=dev

# General settings Spring Boot
spring.main.banner-mode=console
spring.jpa.open-in-view=false

# General bot settings
telegram.bot.token=${BOT_TOKEN:7513242957:AAFPc3-0epTXzSZAIJfLCGxbHd1g5l0NA9g}