# Logging
logging.level.pro.sky.telegrambot=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Database (development)
spring.datasource.url=jdbc:postgresql://localhost:5433/telegram_bot01
spring.datasource.username=SendMeReminder
spring.datasource.password=QwertY
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate (development)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml





# Debugging
server.error.include-stacktrace=always